apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: mern-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: vikashsharma0707/backend:latest

          ports:
            - containerPort: 5000

          env:
            - name: PORT
              value: "5000"

            - name: MONGO_URI
              value: "YOUR_MONGODB_ATLAS_URI"